

#ifndef _KEY_LED_TABLE_H_
#define _KEY_LED_TABLE_H_

#define LOC(x, y) 		((((x - 1) & 0xFF) << 8) | ((y - 1) & 0xFF))  	/* 高8 位X 的位置，低8 位Y 的位置 */
#define GET_X(loc)		((loc >> 8) & 0xFF)
#define GET_Y(loc)		(loc & 0xFF)

extern u8 g_u8KeyTable[KEY_Y_CNT][KEY_X_CNT];
enum 
{
	_Key_Record_Record = 1,
	_Key_Record_Live,
	_Key_Record_Snap,
	_Key_Record_ChannelRecord,

	_Key_Delay_Broadcast_Live_Stop,
	_Key_Delay_Broadcast_Express,
	_Key_Delay_Broadcast_Safe,

	_Key_Caption,
	_Key_Angle1,
	_Key_Angle2,
	_Key_Time,

	_Key_VI_V1,
	_Key_VI_V2,
	_Key_VI_V3,
	_Key_VI_V4,
	_Key_VI_1,
	_Key_VI_2,
	_Key_VI_3,
	_Key_VI_4,
	_Key_VI_Auto,

	_Key_DDR_1,
	_Key_DDR_2,
	_Key_DDR_Back,
	_Key_DDR_Stop,
	_Key_DDR_Play_Pause,
	_Key_DDR_Front,
	_Key_DDR_Cycle,
	_Key_DDR_Single,
	_Key_DDR_Auto,

	_Key_PGM_1,
	_Key_PGM_2,
	_Key_PGM_3,
	_Key_PGM_4,
	_Key_PGM_VGA,
	_Key_PGM_NET,
	_Key_PGM_DDR1,
	_Key_PGM_DDR2,
	_Key_PGM_V1,
	_Key_PGM_V2,
	_Key_PGM_V3,
	_Key_PGM_V4,

	_Key_PVW_1,
	_Key_PVW_2,
	_Key_PVW_3,
	_Key_PVW_4,
	_Key_PVW_VGA,
	_Key_PVW_NET,
	_Key_PVW_DDR1,
	_Key_PVW_DDR2,
	_Key_PVW_V1,
	_Key_PVW_V2,
	_Key_PVW_V3,
	_Key_PVW_V4,

	_Key_Trick_Fade_IN_OUT,
	_Key_Trick_Left_Erasure,
	_Key_Trick_Reel,
	_Key_Trick_PIP,
	_Key_Trick_Shortcut_1,
	_Key_Trick_Shortcut_2,
	_Key_Trick_Shortcut_3,
	_Key_Trick_Shortcut_4,
	_Key_Trick_Shortcut_5,
	_Key_Trick_Shortcut_6,
	_Key_Trick_Shortcut_7,
	_Key_Trick_Shortcut_8,

	_Key_Positoin_1,
	_Key_Positoin_2,
	_Key_Positoin_3,
	_Key_Positoin_4,
	_Key_Positoin_VIN_1,
	_Key_Positoin_VIN_2,
	_Key_Positoin_VIN_3,
	_Key_Positoin_VIN_4,
	_Key_Positoin_ZOOM,
	_Key_Positoin_Caption,
	_Key_Positoin_Angle1,
	_Key_Positoin_Angle2,
	_Key_Positoin_Time,
	_Key_Positoin_Aus,

	_Key_Cutover_PVM,
	_Key_Cutover_PGW,
	_Key_Cutover_FTB,
	_Key_Cutover_VI,
	_Key_Cutover_Cut,
	_Key_Cutover_Auto,

	_Key_Switch_1,
	_Key_Switch_2,
	_Key_Switch_3,
	_Key_Switch_4,


	_Key_Cam_Ctrl_Reserved,

};


enum 
{
	_Led_Record_Record = LOC(1, 1),
	_Led_Record_Live = LOC (2, 1),
	_Led_Record_Snap = LOC(3, 1),
	_Led_Record_ChannelRecord = LOC(4, 1),

	_Led_Delay_Broadcast_Live = LOC(2, 4),
	_Led_Delay_Broadcast_Stop = LOC(3, 4),
	_Led_Delay_Broadcast_Express = LOC(6, 1),
	_Led_Delay_Broadcast_Safe = LOC(7, 1),

	_Led_Caption = LOC(8, 1),
	_Led_Angle1 = LOC(1, 3),
	_Led_Angle2 = LOC(2, 3),
	_Led_Time = LOC(3, 3),

	_Led_VI_V1 = LOC(1, 2),
	_Led_VI_V2 = LOC(2, 2),
	_Led_VI_V3 = LOC(3, 2),
	_Led_VI_V4 = LOC(4, 2),
	_Led_VI_1 = LOC(5, 2),
	_Led_VI_2 = LOC(6, 2),
	_Led_VI_3 = LOC(7, 2),
	_Led_VI_4 = LOC(8, 2),
	_Led_VI_Auto = LOC(1, 4),

	_Led_DDR_1 = LOC(4, 3),
	_Led_DDR_2 = LOC(4, 4),
	_Led_DDR_Back = LOC(5, 3),
	_Led_DDR_Play  = LOC(3, 10),
	_Led_DDR_Pause = LOC(4, 10),
	_Led_DDR_Stop = LOC(6, 4),
	_Led_DDR_Front = LOC(5, 4),
	_Led_DDR_Cycle = LOC(7, 3),
	_Led_DDR_Single = LOC(7, 4),
	_Led_DDR_Auto = LOC(8, 3),

	_Led_PGM_1 = LOC(1, 5),
	_Led_PGM_2 = LOC(2, 5),
	_Led_PGM_3 = LOC(3, 5),
	_Led_PGM_4 = LOC(4, 5),
	_Led_PGM_VGA = LOC(5, 5),
	_Led_PGM_NET = LOC(6, 5),
	_Led_PGM_DDR1 = LOC(7, 5),
	_Led_PGM_DDR2 = LOC(8, 5),
	_Led_PGM_V1 = LOC(1, 7),
	_Led_PGM_V2 = LOC(2, 7),
	_Led_PGM_V3 = LOC(3, 7),
	_Led_PGM_V4 = LOC(4, 7),

	_Led_PVW_1 = LOC(1, 6),
	_Led_PVW_2 = LOC(2, 6),
	_Led_PVW_3 = LOC(3, 6),
	_Led_PVW_4 = LOC(4, 6),
	_Led_PVW_VGA = LOC(5, 6),
	_Led_PVW_NET = LOC(6, 6),
	_Led_PVW_DDR1 = LOC(7, 6),
	_Led_PVW_DDR2 = LOC(8, 6),
	_Led_PVW_V1 = LOC(1, 8),
	_Led_PVW_V2 = LOC(2, 8),
	_Led_PVW_V3 = LOC(3, 8),
	_Led_PVW_V4 = LOC(4, 8),

	_Led_Trick_Fade_IN_OUT = LOC(5, 7),
	_Led_Trick_Left_Erasure = LOC(6, 7),
	_Led_Trick_Reel = LOC(7, 7),
	_Led_Trick_PIP = LOC(8, 7),
	_Led_Trick_Shortcut_1 = LOC(5, 8),
	_Led_Trick_Shortcut_2 = LOC(6, 8),
	_Led_Trick_Shortcut_3 = LOC(7, 8),
	_Led_Trick_Shortcut_4 = LOC(8, 8),
	_Led_Trick_Shortcut_5 = LOC(1, 9),
	_Led_Trick_Shortcut_6 = LOC(2, 9),
	_Led_Trick_Shortcut_7 = LOC(3, 9),
	_Led_Trick_Shortcut_8 = LOC(4, 9),

	_Led_Positoin_1 = LOC(1, 11),
	_Led_Positoin_2 = LOC(2, 11),
	_Led_Positoin_3 = LOC(3, 11),
	_Led_Positoin_4 = LOC(4, 11),
	_Led_Positoin_VIN_1 = LOC(1, 12),
	_Led_Positoin_VIN_2 = LOC(2, 12),
	_Led_Positoin_VIN_3 = LOC(3, 12),
	_Led_Positoin_VIN_4 = LOC(4, 12),
	_Led_Positoin_ZOOM = LOC(5, 11),
	_Led_Positoin_Caption = LOC(5, 9),
	_Led_Positoin_Angle1 = LOC(6, 9),
	_Led_Positoin_Angle2 = LOC(7, 9),
	_Led_Positoin_Time = LOC(8, 9),

	_Led_Cutover_PVM = LOC(5, 10),
	_Led_Cutover_PGW = LOC(6, 10),
	_Led_Cutover_FTB = LOC(7, 10),
	_Led_Cutover_VI = LOC(8, 10),
	_Led_Cutover_Cut = LOC(1, 10),
	_Led_Cutover_Auto = LOC(2, 10),

	_Led_Switch_1_1 = LOC(9, 1),
	_Led_Switch_1_2 = LOC(10, 1),
	_Led_Switch_1_3 = LOC(11, 1),
	_Led_Switch_1_4 = LOC(12, 1),
	_Led_Switch_1_5 = LOC(13, 1),
	_Led_Switch_1_6 = LOC(14, 1),
	_Led_Switch_1_7 = LOC(15, 1),
	_Led_Switch_1_8 = LOC(16, 1),

	_Led_Switch_2_1 = LOC(9, 2),
	_Led_Switch_2_2 = LOC(10, 2),
	_Led_Switch_2_3 = LOC(11, 2),
	_Led_Switch_2_4 = LOC(12, 2),
	_Led_Switch_2_5 = LOC(13, 2),
	_Led_Switch_2_6 = LOC(14, 2),
	_Led_Switch_2_7 = LOC(15, 2),
	_Led_Switch_2_8 = LOC(16, 2),

	_Led_Switch_3_1 = LOC(9, 3),
	_Led_Switch_3_2 = LOC(10, 3),
	_Led_Switch_3_3 = LOC(11, 3),
	_Led_Switch_3_4 = LOC(12, 3),
	_Led_Switch_3_5 = LOC(13, 3),
	_Led_Switch_3_6 = LOC(14, 3),
	_Led_Switch_3_7 = LOC(15, 3),
	_Led_Switch_3_8 = LOC(16, 3),

	_Led_Switch_4_1 = LOC(9, 4),
	_Led_Switch_4_2 = LOC(10, 4),
	_Led_Switch_4_3 = LOC(11, 4),
	_Led_Switch_4_4 = LOC(12, 4),
	_Led_Switch_4_5 = LOC(13, 4),
	_Led_Switch_4_6 = LOC(14, 4),
	_Led_Switch_4_7 = LOC(15, 4),
	_Led_Switch_4_8 = LOC(16, 4),

	_Led_TPush_1 = LOC(9, 5),
	_Led_TPush_2 = LOC(10, 5),
	_Led_TPush_3 = LOC(11, 5),
	_Led_TPush_4 = LOC(12, 5),
	_Led_TPush_5 = LOC(13, 5),
	_Led_TPush_6 = LOC(14, 5),
	_Led_TPush_7 = LOC(15, 5),
	_Led_TPush_8 = LOC(16, 5),

	_Led_Voice_1 = LOC(16, 7),
	_Led_Voice_2 = LOC(15, 7),
	_Led_Voice_3 = LOC(14, 7),
	_Led_Voice_4 = LOC(13, 7),
	_Led_Voice_5 = LOC(12, 7),
	_Led_Voice_6 = LOC(11, 7),
	_Led_Voice_7 = LOC(10, 7),
	_Led_Voice_8 = LOC(9, 7),
	_Led_Voice_9 = LOC (16, 8),
	_Led_Voice_10 = LOC(15, 8),
	_Led_Voice_11 = LOC(14, 8),
	_Led_Voice_12 = LOC(13, 8),
	_Led_Voice_13 = LOC(12, 8),
	_Led_Voice_14 = LOC(11, 8),
	_Led_Voice_15 = LOC(10, 8),
	_Led_Voice_16 = LOC(9, 8),
	_Led_Voice_17 = LOC(16, 9),
	_Led_Voice_18 = LOC(15, 9),
	_Led_Voice_19 = LOC(14, 9),
	_Led_Voice_20 = LOC(13, 9),
	_Led_Voice_21 = LOC(12, 9),
	_Led_Voice_22 = LOC(11, 9),
	_Led_Voice_23 = LOC(10, 9),
	_Led_Voice_24 = LOC(9, 9),
                         
	_Led_Rock_1 = LOC(9, 10),
	_Led_Rock_2 = LOC(10, 10),
	_Led_Rock_3 = LOC(11, 10),
	_Led_Rock_4 = LOC(12, 10),
	_Led_Rock_5 = LOC(13, 10),
	_Led_Rock_6 = LOC(14, 10),
	_Led_Rock_7 = LOC(15, 10),
	_Led_Rock_8 = LOC(16, 10),

};

#endif

